DROP TABLE IF EXISTS PETS;
CREATE TABLE PETS (
                      id bigint GENERATED BY DEFAULT AS IDENTITY,
                      name VARCHAR(255) NOT NULL,
                      code VARCHAR(255) NOT NULL,
                      type VARCHAR(255) NOT NULL,
                      fur_color VARCHAR(255),
                      country_of_origin VARCHAR(255),
                      owner_id int,
                      PRIMARY KEY (id)
);

