DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
                      id bigint GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR(255) NOT NULL,
                      password VARCHAR(255) NOT NULL
);

INSERT INTO USERS (username, password)  VALUES ('admin', 'admin'), ('user', 'userpass'), ('q', 'q');
